/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef CSV_CONFIG_MGR_IMPL_H_H_HHHH
#define CSV_CONFIG_MGR_IMPL_H_H_HHHH

#include "structs_py.h"
#include "detail_config_py.h"

class CConfigPy
{
public:
	bool BaseLoad();
public:
    const CHeroQualityUpTest &GetHeroQualityUpTest() const { return m_oHeroQualityUpTest;}
    const CVipLevelTest &GetVipLevelTest() const { return m_oVipLevelTest;}

private:
    CHeroQualityUpTest m_oHeroQualityUpTest;
    CVipLevelTest m_oVipLevelTest;

};
#endif /* CSV_CONFIG_MGR_IMPL_H_H_HHHH */