/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#include "CSVConfigHead.h"

#if defined(WIN32) || defined(WIN64)
#else
#include <stdio.h>
#include <unistd.h>
#include <dirent.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <string.h>
#include <assert.h>
#endif

#Begin_Replace_Tag_Class
bool #ClsName::Load(const std::string & szFileName)
{
	try
	{
		csv::CSVParser oParser = csv::CSVParser(szFileName);
		for (int i = 3; i < oParser.RowCount(); ++i) {
			#StructName conent;
		    int nColumn = 1;
		    #KeyTypeName #KeyName = atoi(oParser.GetField(i, nColumn++).c_str());
		    conent.#KeyName = #KeyName;
		    #KeyTypeName llKey = #KeyName;
#Begin_Replace_Tag_Attri
			conent.#AttriName = oParser.#AttriType2FuncName(i, nColumn++);
#End_Replace_Tag_Attri
		    m_map#FileName[llKey] = conent;
		}
	}
	catch (const std::exception&)
	{
		return false;
	}
	
	return true;
}
const #StructName *#ClsName::FindContent(#KeyTypeName	#KeyName) const
{
	int llKey = #KeyName;

	auto it = m_map#FileName.find(llKey);
	if (it != m_map#FileName.end())
	{
		return &it->second;
	}
	return NULL;
}
#End_Replace_Tag_Class
