/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#include "CSVConfigMgrImpl.h"

bool CConfigPy::BaseLoad()
{
	char szFileExePath[MAX_PATH] = {0};
	const char *pszExePath = "";
	const string pathFormatStr = "%s/../../config/%s.csv";
	const string errorFormatStr = "load %s error";
	snprintf(szFileExePath, sizeof(szFileExePath) - 1, pathFormatStr, pszExePath, HeroQualityUpTest);
	if (!m_oHeroQualityUpTest.Load(szFileExePath)){
		USR_CRITICALEX(true, errorFormatStr, szFileExePath);
		return false;
	}
	snprintf(szFileExePath, sizeof(szFileExePath) - 1, pathFormatStr, pszExePath, VipLevelTest);
	if (!m_oVipLevelTest.Load(szFileExePath)){
		USR_CRITICALEX(true, errorFormatStr, szFileExePath);
		return false;
	}

	return true;
}
