/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef CSV_CONFIG_MGR_IMPL_H_H_HHHH
#define CSV_CONFIG_MGR_IMPL_H_H_HHHH

#include "structs_py.h"
#include "detail_config_py.h"

class CConfigPy
{
public:
	bool BaseLoad();
public:
#Begin_Replace_Tag_Class
    const #ClsName &Get#FileName() const { return m_o#FileName;}
#End_Replace_Tag_Class
private:
#Begin_Replace_Tag_Class
    #ClsName m_o#FileName;
#End_Replace_Tag_Class
};
#endif /* CSV_CONFIG_MGR_IMPL_H_H_HHHH */