/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#include "CSVConfigMgrImpl.h"

bool CConfigPy::BaseLoad()
{
	char szFileExePath[MAX_PATH] = {0};
	const char *pszExePath = "";
	const string pathFormatStr = "%s/../../config/%s.csv";
	const string errorFormatStr = "load %s error";
#Begin_Replace_Tag_Class
	snprintf(szFileExePath, sizeof(szFileExePath) - 1, pathFormatStr, pszExePath, #FileName);
	if (!m_o#FileName.Load(szFileExePath)){
		USR_CRITICALEX(true, errorFormatStr, szFileExePath);
		return false;
	}
#End_Replace_Tag_Class
	return true;
}
